//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order_WebApi.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Order
    {
        public int ID { get; set; }
        public int Staff_ID { get; set; }
        public string Customer_Name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> Total_Payment { get; set; }
        public Nullable<int> Store_ID { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CheckoutDate { get; set; }
    }
}
